[build-options]
  observabilityIncluded = true

[package]
  distribution = "2201.3.1"
  export = ["data_mapping"]
  icon = "docs/icon.png"
  keywords = ["Kind/Sample","Type/Service","Category/Service","Internal/http"]
  name = "data_mapping"
  org = "rkconsulting"
  version = "3.1.1"

